### ISSUE TITLE
文件找不到

### ISSUE THREAD

**Issue by Ingram-lin** [thuhcsi/LightGrad#2]
meatadata.csv.txt 文件找不到

**Comment by unrea1-sama** [comment]
Download dataset from https://www.data-baker.com/data/index/TNtts/ . 

Extract all files and you will get a directory whose structure is:
```
|-标贝开源数据产品说明书_【中文标准女声音库】.pdf  
|-PhoneLabeling    
|-Wave
|-英文TTS音素标注规范.pdf                          
|-ProsodyLabeling  
|-Wave.48k
|-中文TTS音素标注规范.pdf                          
|-readme.txt
|-metadata.csv.txt                                 
|-Scripts
```
Then, run preprocess script and set [PATH_TO_DIRECTORY_CONTAINING_DATASET] to the directory given above.

**Comment by Ingram-lin** [comment]
非常感谢您的回复，我复现了中文部分，虽然成功推理了，但是生成的语音效果很差，可以方便和您进一步交流吗？
Thank you very much for your response. I have reproduced the Chinese part, and although the inference was successful, the generated speech quality is poor. Can we communicate further to discuss this?

**Comment by unrea1-sama** [comment]
Could you please upload generated samples?

**Comment by Ingram-lin** [comment]
sure,This is the text:梁朝伟演色戒刘嘉玲也顶不住
output is the streaming interfence




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuhcsi/LightGrad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuhcsi/LightGrad] 文件找不到 (Issue #2)





 
Could you please upload generated samples?

**Comment by Ingram-lin** [comment]
Can I send u by email?

**Comment by Ingram-lin** [comment]
Can I send u by email?

**Comment by Ingram-lin** [comment]
Sry,I don't know how to post in this issue.  Can I send u by email?

**Comment by unrea1-sama** [comment]
You can upload your file by dragging & dropping when you edit the reply.

![图片](https://github.com/thuhcsi/LightGrad/assets/27909669/c8062f72-b5c4-4df5-ac91-2412583863cb)

**Comment by Ingram-lin** [comment]
<img width="338" alt="WeChate8c86fdabf77fe56397de8a96407fa38" src="https://github.com/thuhcsi/LightGrad/assets/82919905/764907d6-9098-4c5e-bc35-1c1af1f5e28f">
I'm sorry, I haven't uploaded anything on GitHub before. 
I have tried changing the audio format as shown in the image, but I still cannot upload it. Can you give me some other suggestions?

**Comment by yangqi0530** [comment]
> meatadata.csv.txt 文件找不到

请问后面你是在哪里下载的,我在链接直接点击下载后安装包内只有三个文件夹

**Comment by unrea1-sama** [comment]
You can send your files to unrea1sama@outlook.com

**Comment by Ingram-lin** [comment]
> > meatadata.csv.txt 文件找不到
> 
> 请问后面你是在哪里下载的,我在链接直接点击下载后安装包内只有三个文件夹

您好 解决了吗？没有解决的话我们进一步交流

**Comment by yangqi0530** [comment]
> > > meatadata.csv.txt 文件找不到
> > 
> > 
> > 请问后面你是在哪里下载的,我在链接直接点击下载后安装包内只有三个文件夹
> 
> 您好 解决了吗？没有解决的话我们进一步交流

已经邮件请教了,回复表示后面会更新预处理代码.请问其他人有metadataa.csv.txt的文件吗?

**Comment by Ingram-lin** [comment]
> > > > meatadata.csv.txt 文件找不到
> > > 
> > > 
> > > 请问后面你是在哪里下载的,我在链接直接点击下载后安装包内只有三个文件夹
> > 
> > 
> > 您好 解决了吗？没有解决的话我们进一步交流
> 
> 已经邮件请教了,回复表示后面会更新预处理代码.请问其他人有metadataa.csv.txt的文件吗?

可以给我邮箱嘛？我发给你我处理过的

**Comment by yangqi0530** [comment]
> > > > > meatadata.csv.txt 文件找不到
> > > > 
> > > > 
> > > > 请问后面你是在哪里下载的,我在链接直接点击下载后安装包内只有三个文件夹
> > > 
> > > 
> > > 您好 解决了吗？没有解决的话我们进一步交流
> > 
> > 
> > 已经邮件请教了,回复表示后面会更新预处理代码.请问其他人有metadataa.csv.txt的文件吗?
> 
> 可以给我邮箱嘛？我发给你我处理过的

1014102811@qq.com , 非常感谢

**Comment by liao-h-c** [comment]
> > > > > meatadata.csv.txt 文件找不到
> > > > 
> > > > 
> > > > 请问后面你是在哪里下载的,我在链接直接点击下载后安装包内只有三个文件夹
> > > 
> > > 
> > > 您好 解决了吗？没有解决的话我们进一步交流
> > 
> > 
> > 已经邮件请教了,回复表示后面会更新预处理代码.请问其他人有metadataa.csv.txt的文件吗?
> 
> 可以给我邮箱嘛？我发给你我处理过的

您好，请问可以把处理过的metadata.csv.txt文件也发给我一份到3072806964@qq.com，非常感谢

**Comment by unrea1-sama** [comment]
The preprocess script for BZNSYP has been updated.
However, as I don't have a GPU server right now, preprocessed dataset generated by new preprocess script has not been tested by retraining a new model.
